### ISSUE TITLE
Bryant's first infra project

### ISSUE THREAD

**Issue by parchinski** [HackUCF/my-first-infra-project#2]
bryantpdev

**Comment by parchinski** [comment]
I am receiving errors when trying to create my image in openstack

**Comment by Idle-Truth** [comment]
Don't forget to add the snapshot of your instance in openstack and your terminal when you first ssh into your instance.

**Comment by parchinski** [comment]
<img width="1271" alt="Screenshot 2024-09-05 at 5 59 28 PM" src="https://github.com/user-attachments/assets/24316c8c-5bc4-402d-9262-00fc2f84b489">

**Comment by parchinski** [comment]
<img width="1271" alt="image" src="https://github.com/user-attachments/assets/cad672ed-e446-44bf-9d00-82785a86fc61">

**Comment by parchinski** [comment]
> Don't forget to add the snapshot of your instance in openstack and your terminal when you first ssh into your instance.

Done!
